import type { ServiceWorkflow } from '@/types/wizard'

export const cambioDeEstatusWorkflow: ServiceWorkflow = {
  slug: 'cambio-de-estatus',
  name: 'Cambio de Estatus (B-2 a F-1)',
  steps: [
    {
      step: 1,
      title: 'Información Personal',
      description: 'Datos personales del solicitante para el Formulario I-539',
      type: 'form',
      fields: [
        { key: 'legal_last_name', label: 'Apellido legal', type: 'text', required: true },
        { key: 'legal_first_name', label: 'Nombre legal', type: 'text', required: true },
        { key: 'legal_middle_name', label: 'Segundo nombre', type: 'text' },
        {
          key: 'other_names',
          label: 'Otros nombres usados',
          type: 'text_array',
          helper: 'Incluya nombres de soltera, alias, o cualquier otro nombre',
        },
        { key: 'date_of_birth', label: 'Fecha de nacimiento', type: 'date', required: true },
        { key: 'city_of_birth', label: 'Ciudad de nacimiento', type: 'text', required: true },
        { key: 'country_of_birth', label: 'País de nacimiento', type: 'country_select', required: true },
        { key: 'nationality', label: 'Nacionalidad', type: 'country_select', required: true },
        {
          key: 'gender',
          label: 'Sexo',
          type: 'select',
          options: ['Masculino', 'Femenino'],
          required: true,
        },
        {
          key: 'marital_status',
          label: 'Estado civil',
          type: 'select',
          options: ['Soltero/a', 'Casado/a', 'Divorciado/a', 'Viudo/a'],
          required: true,
        },
        { key: 'ssn', label: 'Número de Seguro Social (SSN)', type: 'text' },
        {
          key: 'a_number',
          label: 'Número A (Alien Number)',
          type: 'text',
          helper: "Si tiene uno, comienza con 'A' seguido de 8 o 9 dígitos",
        },
        { key: 'uscis_account', label: 'Número de cuenta USCIS en línea', type: 'text' },
        { key: 'residence_address_street', label: 'Dirección de residencia (calle)', type: 'text', required: true },
        { key: 'residence_address_city', label: 'Ciudad', type: 'text', required: true },
        { key: 'residence_address_state', label: 'Estado', type: 'us_state_select', required: true },
        { key: 'residence_address_zip', label: 'Código postal', type: 'text', required: true },
        { key: 'phone', label: 'Teléfono', type: 'phone', required: true },
        { key: 'email', label: 'Correo electrónico', type: 'email', required: true },
      ],
    },
    {
      step: 2,
      title: 'Información Migratoria Actual',
      description: 'Detalles de su estatus actual y entrada a EE.UU.',
      type: 'form',
      fields: [
        {
          key: 'current_status',
          label: 'Estatus migratorio actual',
          type: 'select',
          options: ['B-1 (Negocios)', 'B-2 (Turismo)', 'B-1/B-2', 'Otro'],
          required: true,
        },
        {
          key: 'current_status_other',
          label: 'Especifique otro estatus',
          type: 'text',
          conditional: "current_status === 'Otro'",
        },
        {
          key: 'last_entry_date',
          label: 'Fecha de última entrada a EE.UU.',
          type: 'date',
          required: true,
        },
        {
          key: 'entry_place',
          label: 'Lugar de entrada (puerto/aeropuerto)',
          type: 'text',
          required: true,
          helper: 'Ej: Miami International Airport, LAX, JFK',
        },
        { key: 'i94_number', label: 'Número I-94', type: 'text', required: true },
        {
          key: 'i94_expiration',
          label: 'Fecha de expiración del I-94 / estatus actual',
          type: 'date',
          required: true,
          helper: 'Puede verificar en i94.cbp.dhs.gov',
        },
        { key: 'passport_number', label: 'Número de pasaporte', type: 'text', required: true },
        { key: 'passport_country', label: 'País del pasaporte', type: 'country_select', required: true },
        { key: 'passport_expiry', label: 'Fecha de expiración del pasaporte', type: 'date', required: true },
        {
          key: 'visa_number',
          label: 'Número de visa (en la estampa del pasaporte)',
          type: 'text',
        },
        {
          key: 'visa_expiry',
          label: 'Fecha de expiración de la visa',
          type: 'date',
        },
        {
          key: 'previous_cos',
          label: '¿Ha solicitado cambio de estatus anteriormente?',
          type: 'boolean',
        },
        {
          key: 'previous_cos_details',
          label: 'Detalles de solicitudes anteriores',
          type: 'long_text',
          conditional: 'previous_cos === true',
          helper: 'Incluya fecha, tipo de solicitud, y resultado',
        },
        {
          key: 'entries_to_us',
          label: 'Historial de entradas a EE.UU. (últimos 5 años)',
          type: 'repeatable_group',
          helper: 'Liste todas las entradas a EE.UU. en los últimos 5 años',
          subfields: [
            { key: 'entry_date', label: 'Fecha de entrada', type: 'date' },
            { key: 'entry_location', label: 'Lugar de entrada', type: 'text' },
            { key: 'entry_visa_status', label: 'Estatus de entrada', type: 'text' },
            { key: 'departure_date', label: 'Fecha de salida', type: 'date' },
          ],
        },
      ],
    },
    {
      step: 3,
      title: 'Información Escolar',
      description: 'Datos de la escuela y programa de estudios al que desea cambiar',
      type: 'form',
      fields: [
        {
          key: 'school_name',
          label: 'Nombre de la escuela o institución educativa',
          type: 'text',
          required: true,
          helper: 'Debe ser una escuela certificada por SEVP',
        },
        {
          key: 'school_address',
          label: 'Dirección de la escuela',
          type: 'text',
          required: true,
        },
        {
          key: 'school_city',
          label: 'Ciudad',
          type: 'text',
          required: true,
        },
        {
          key: 'school_state',
          label: 'Estado',
          type: 'us_state_select',
          required: true,
        },
        {
          key: 'sevp_certified',
          label: '¿La escuela está certificada por SEVP?',
          type: 'boolean',
          required: true,
          helper: 'Verifique en studyinthestates.dhs.gov',
        },
        {
          key: 'sevis_id',
          label: 'SEVIS School Code',
          type: 'text',
          helper: 'Aparece en el Formulario I-20 emitido por la escuela',
        },
        {
          key: 'program_type',
          label: 'Tipo de programa',
          type: 'select',
          options: ['Idioma/ESL', 'Certificado/Diploma', 'Associate (2 años)', 'Bachelor (4 años)', 'Maestría', 'Doctorado', 'Otro'],
          required: true,
        },
        {
          key: 'program_name',
          label: 'Nombre del programa de estudios',
          type: 'text',
          required: true,
          helper: 'Ej: English as a Second Language, Business Administration, Computer Science',
        },
        {
          key: 'program_start_date',
          label: 'Fecha de inicio del programa',
          type: 'date',
          required: true,
        },
        {
          key: 'program_end_date',
          label: 'Fecha estimada de finalización',
          type: 'date',
        },
        {
          key: 'has_i20',
          label: '¿Ya tiene el Formulario I-20 de la escuela?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'i20_issue_date',
          label: 'Fecha de emisión del I-20',
          type: 'date',
          conditional: 'has_i20 === true',
        },
        {
          key: 'admission_cost',
          label: 'Costo estimado de matrícula (por semestre o año)',
          type: 'currency',
          helper: 'En dólares USD',
        },
      ],
    },
    {
      step: 4,
      title: 'Información Financiera',
      description: 'Evidencia de que puede financiar sus estudios en EE.UU.',
      type: 'form',
      fields: [
        {
          key: 'funding_source',
          label: 'Fuente principal de financiamiento',
          type: 'select',
          options: [
            'Recursos propios',
            'Patrocinador familiar',
            'Beca de la escuela',
            'Gobierno de mi país',
            'Combinación de fuentes',
            'Otro',
          ],
          required: true,
        },
        {
          key: 'funding_other',
          label: 'Especifique otra fuente',
          type: 'text',
          conditional: "funding_source === 'Otro'",
        },
        {
          key: 'annual_funds_available',
          label: 'Fondos anuales disponibles para estudios (USD)',
          type: 'currency',
          required: true,
          helper: 'Debe cubrir matrícula + gastos de vida (~$15,000-$30,000/año según ubicación)',
        },
        {
          key: 'has_sponsor',
          label: '¿Tiene un patrocinador financiero?',
          type: 'boolean',
        },
        {
          key: 'sponsor_name',
          label: 'Nombre completo del patrocinador',
          type: 'text',
          conditional: 'has_sponsor === true',
        },
        {
          key: 'sponsor_relationship',
          label: 'Relación con el patrocinador',
          type: 'select',
          options: ['Padre/Madre', 'Cónyuge', 'Hermano/a', 'Tío/a', 'Abuelo/a', 'Otro familiar', 'Amigo', 'Empleador', 'Otro'],
          conditional: 'has_sponsor === true',
        },
        {
          key: 'sponsor_address',
          label: 'Dirección del patrocinador',
          type: 'text',
          conditional: 'has_sponsor === true',
        },
        {
          key: 'sponsor_income',
          label: 'Ingreso anual del patrocinador (USD)',
          type: 'currency',
          conditional: 'has_sponsor === true',
        },
      ],
    },
    {
      step: 5,
      title: 'Familiares Incluidos (si aplica)',
      description: 'Si solicita cambio de estatus para familiares también',
      type: 'form',
      fields: [
        {
          key: 'include_dependents',
          label: '¿Desea incluir familiares en la solicitud?',
          type: 'boolean',
          required: true,
          helper: 'Cónyuge (F-2) e hijos solteros menores de 21 años',
        },
        {
          key: 'dependents',
          label: 'Familiares a incluir',
          type: 'repeatable_group',
          conditional: 'include_dependents === true',
          subfields: [
            { key: 'dep_last_name', label: 'Apellido', type: 'text' },
            { key: 'dep_first_name', label: 'Nombre', type: 'text' },
            { key: 'dep_dob', label: 'Fecha de nacimiento', type: 'date' },
            { key: 'dep_country', label: 'País de nacimiento', type: 'country_select' },
            {
              key: 'dep_relationship',
              label: 'Relación',
              type: 'select',
              options: ['Cónyuge', 'Hijo/a'],
            },
            { key: 'dep_passport_number', label: 'Número de pasaporte', type: 'text' },
            { key: 'dep_i94_number', label: 'Número I-94', type: 'text' },
            { key: 'dep_current_status', label: 'Estatus actual', type: 'text' },
          ],
        },
      ],
    },
    {
      step: 6,
      title: 'Documentos de Soporte',
      description: 'Suba los documentos requeridos para la solicitud I-539',
      type: 'documents',
    },
    {
      step: 7,
      title: 'Revisión y Firma',
      description: 'Revise toda la información antes de enviar su solicitud de cambio de estatus',
      type: 'review',
    },
  ],
  required_documents: [
    { key: 'passport', label: 'Pasaporte vigente (todas las páginas con sellos)', required: true, category: 'identidad' },
    {
      key: 'passport_photos',
      label: 'Fotos tipo pasaporte',
      required: true,
      category: 'identidad',
      helper: '2 fotos tamaño pasaporte recientes (fondo blanco)',
    },
    { key: 'photo_id', label: 'Identificación con foto', required: true, category: 'identidad' },
    {
      key: 'i94',
      label: 'Registro I-94 (más reciente)',
      required: true,
      category: 'inmigración',
      helper: 'Descargue en i94.cbp.dhs.gov',
    },
    {
      key: 'visa_stamp',
      label: 'Copia de la estampa de visa B-1/B-2',
      required: true,
      category: 'inmigración',
    },
    {
      key: 'i20',
      label: 'Formulario I-20 emitido por la escuela',
      required: true,
      category: 'escolar',
      helper: 'Emitido por el DSO de la escuela certificada por SEVP, indicando "cambio de estatus"',
    },
    {
      key: 'admission_letter',
      label: 'Carta de admisión de la escuela',
      required: true,
      category: 'escolar',
    },
    {
      key: 'sevis_fee_receipt',
      label: 'Comprobante de pago de la tarifa SEVIS I-901',
      required: true,
      category: 'escolar',
      helper: 'Pago realizado en fis.gov ($350 USD)',
    },
    {
      key: 'bank_statements',
      label: 'Estados de cuenta bancarios',
      required: true,
      category: 'financiero',
      multiple: true,
      helper: 'Últimos 3 meses. Deben mostrar fondos suficientes para cubrir matrícula y gastos de vida',
    },
    {
      key: 'sponsor_affidavit',
      label: 'Carta de apoyo financiero del patrocinador',
      required: false,
      category: 'financiero',
      helper: 'Si otra persona financia sus estudios, incluya carta notarizada y estados de cuenta del patrocinador',
    },
    {
      key: 'sponsor_bank_statements',
      label: 'Estados de cuenta del patrocinador',
      required: false,
      category: 'financiero',
      multiple: true,
    },
    {
      key: 'tax_returns',
      label: 'Declaraciones de impuestos (patrocinador)',
      required: false,
      category: 'financiero',
      multiple: true,
      helper: 'Últimos 2 años si el patrocinador reside en EE.UU.',
    },
    {
      key: 'scholarship_letter',
      label: 'Carta de beca o ayuda financiera',
      required: false,
      category: 'financiero',
      helper: 'Si la escuela le otorgó beca parcial o completa',
    },
    {
      key: 'dependent_passports',
      label: 'Pasaportes de familiares incluidos',
      required: false,
      category: 'familia',
      multiple: true,
      helper: 'Solo si incluye cónyuge o hijos menores en la solicitud',
    },
    {
      key: 'marriage_certificate',
      label: 'Acta de matrimonio',
      required: false,
      category: 'familia',
      helper: 'Si incluye cónyuge en la solicitud',
    },
    {
      key: 'birth_certificates_dependents',
      label: 'Actas de nacimiento de hijos',
      required: false,
      category: 'familia',
      multiple: true,
      helper: 'Si incluye hijos menores en la solicitud',
    },
  ],
  eligibility_questions: [
    {
      id: 'in_us',
      question: '¿Se encuentra actualmente en EE.UU. con estatus de visa de turismo (B-1/B-2)?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Debe estar físicamente en EE.UU. con estatus B-1/B-2 válido para solicitar cambio de estatus a F-1.',
    },
    {
      id: 'valid_status',
      question: '¿Su estatus migratorio actual (I-94) sigue vigente y no ha expirado?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Su estatus B-1/B-2 debe estar vigente. Si ya expiró, puede no ser elegible para cambio de estatus. Henry evaluará su situación específica.',
    },
    {
      id: 'no_study',
      question: '¿Confirma que NO se ha inscrito ni asistido a clases mientras tiene estatus B-1/B-2?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Asistir a clases con visa de turismo viola las condiciones de su estatus y lo descalifica para el cambio de estatus. Contacte a Henry para evaluar alternativas.',
    },
    {
      id: 'school_accepted',
      question: '¿Ha sido aceptado o está en proceso de admisión en una escuela en EE.UU.?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Necesita ser aceptado en una escuela certificada por SEVP antes de solicitar el cambio de estatus. Henry puede asistirle en el proceso de admisión.',
    },
    {
      id: 'financial_support',
      question: '¿Puede demostrar fondos suficientes para cubrir matrícula y gastos de vida?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Debe demostrar capacidad financiera para cubrir sus estudios. Esto puede ser con fondos propios, patrocinador, o beca.',
    },
  ],
}
